# Site settings
title: The ELIXIR-IIB Training Programme
email: elixir.ita.training@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "https://elixir-iib-training.github.io" # the base hostname & protocol for your site
twitter_username: elixir_ita
#github_username: allegravia  

# Build settings

# I declare _sass as the sass directory, to ensure the Sass compiles correctly
sass:
  sass_dir: _sass

include: ['_pages']

markdown: kramdown
kramdown:
  input: GFM

# adding posts in the future
future: true

# changer server port to 3000
port: 3000
